### ISSUE TITLE
Feature Request: clicking on a dock icon doesn't bring a floating window to the foreground

### ISSUE THREAD

**Issue by anoraktrend** [nwg-piotr/nwg-dock-hyprland#14]
**Describe the feature request**
Clicking on icons don't bring floating windows to the foreground, this is marked as a feature request as it is a missing feature that feels like a bug in practice.

**Additional context**
I use Hyprland with floating windows by default as their workspace switcher is a bit less than ideal for me and my multimonitor setup. This is a feature necessary for this specific setup.

**Comment by nwg-piotr** [comment]
Be patient, please. I'm just packing stuff and leaving for lakes early in the morning. Will get back to it in a week.

**Comment by anoraktrend** [comment]
Don't worry about it, i don't expect an immediate fix, I can wait for a while for this particular issue (seeing as I can use wayfire in the meantime).

**Comment by etherrorcode404** [comment]
I was wondering I would go about deprecating the ".svg" its is quite a pain to the user edit an svg file just to change a few colour configurations, its also inconvient. I love nwg-panel due to everything being user customizable on a simple config file. Can we also implement these?

**Comment by anoraktrend** [comment]
that is entirely unrelated to the issue this issue is about.
