### ISSUE TITLE
Cant change icon colour

### ISSUE THREAD

**Issue by etherrorcode404** [nwg-piotr/nwg-dock-hyprland#15]
How to change application launcher icon (nwg-drawer) icon in the nwg-dock-hyprland? i cant find a css for this. Is the icon an svg? in that case the svg has to be manually modified, the doc isn't very extensive about it.

**Comment by etherrorcode404** [comment]
Also if id like to use a thrid party program like rofi to achieve the app dock, how would i go about making an entry for the icon on the dock?

**Comment by nwg-piotr** [comment]
> How to change application launcher icon

`/usr/share/nwg-dock-hyprland/images/grid.svg` - replace with you own icon image under the same path/name.

```text
$ nwg-dock-hyprland -h
Usage of nwg-dock-hyprland:
  (...)
  -c string
    	Command assigned to the launcher button
  (...)
```

Please read the whole output of the `nwg-dock-hyprland -h` command in the terminal.
