### ISSUE TITLE
Deprecate usage of ".svg"

### ISSUE THREAD

**Issue by etherrorcode404** [nwg-piotr/nwg-dock-hyprland#17]
I was wondering how I would go about deprecating the ".svg" its is quite a pain to the user to have to edit an svg file just to change a few colour configurations, its also inconvient. I love nwg-panel due to everything being user customizable on a simple config file. Can we also implement these?

_Originally posted by @etherrorcode404 in https://github.com/nwg-piotr/nwg-dock-hyprland/issues/14#issuecomment-1675096645_

**Comment by nwg-piotr** [comment]
The obvious solution would be to add a command line argument to specify an alternative icon path / file name for the launcher icon. I can do it next week, as I'm on vacation yet.

**Comment by etherrorcode404** [comment]
> The obvious solution would be to add a command line argument to specify an alternative icon path / file name for the launcher icon. I can do it next week, as I'm on vacation yet.

so can i use css and js to declare my icon?

**Comment by nwg-piotr** [comment]
Nope. It would be an argument to the command you start the dock with, for instance:

```
nwg-dock-hyprland -ico app-launcher
```

to use the `app-launcher` icon from the icon theme, or

```
nwg-dock-hyprland -ico /home/piotr/stuff/my-superb-icon.svg
```

to use a path to an icon.

**Comment by etherrorcode404** [comment]
> 

yes but this will open app dock what if i wanna use something third party? like wofi

**Comment by etherrorcode404** [comment]
Most docks configure the dock icons in css

**Comment by nwg-piotr** [comment]
Use other dock.

**Comment by etherrorcode404** [comment]
Understandable, not everyone wants everything the same way.
However even using -ico throws me an error;

`flag provided but not defined: -ico`

**Comment by nwg-piotr** [comment]
https://github.com/nwg-piotr/nwg-dock-hyprland/issues/17#issuecomment-1675914708

Not yet done. And at the moment - of a low priority.
