### ISSUE TITLE
Icons missing on Nix OS 

### ISSUE THREAD

**Issue by etherbiswas** [nwg-piotr/nwg-dock-hyprland#19]
When using the dock on nixos the application icons appear pixelated and the svg icons don't appear at all, upon further investigation the nix store contains these images which on a distro like arch is at `/usr/share/nwg-dock-hyprland/images/x.svg`

**Comment by etherrorcode404** [comment]
I think this requires nix specific configuration

**Comment by etherrorcode404** [comment]
`/run/current-system/sw/share` it seems is the equivalent of `/usr/share`  in nix

**Comment by nwg-piotr** [comment]
I know nothing on NixOS. And it's not going to change any time soon.

**Comment by etherbiswas** [comment]
This issue can be resloved by modify `/etc/nixos/configuration.nix` by adding this line; 
` boot.readOnlyNixStore = false;` this makes filesystem readable but does really fix the issue entirely. You need to manual copy the content over to `/usr/share/ `  which you can use a symbolic link to acheive. Its quite bit of messing around with the system just to get basic funcationality..

**Comment by nwg-piotr** [comment]
Sorry, but I'm not going to go into how NixOS differs from Linux. If anything can be done on the program side, please submit a PR. Otherwise contact the packager.
