### ISSUE TITLE
Mouse in center of app instead of latest position after selecting app in dock.

### ISSUE THREAD

**Issue by Somnius** [nwg-piotr/nwg-dock-hyprland#28]
From what i understand, when you click an app in the dock, the mouse is placed automatically in the center of the latest active app on the respective workspace.

For example if spotify is in workspace 2 and i'm in workspace 1, and i click spotify on the dock the mouse gets placed on the center of the spotify app. If that app is split in the middle with another the mouse will be placed in the center of e.g. spotify instead of the last place it was.

That may confuse the user.

I'm trying to find more information about this here in `nwg-dock-hyprland` and about the mouse placement.

Are there any opions for the mouse placement ?

**Comment by nwg-piotr** [comment]
What we do on LMB pressed is focusing the corresponding window:

`cmd := fmt.Sprintf("dispatch focuswindow address:%s", t.Address)`

I can't think of another way for it to work.

**Comment by how-to-do-frontend** [comment]
hey guys, i'm not entirely sure if this works yet or not (i don't currently have an env to test on), but i think setting `no_cursor_warps` to true in your hyprland config should do what you want.
from the wiki: if true, will not warp the cursor in many cases (focusing, keybinds, etc)

**Comment by nwg-piotr** [comment]
Yes, it resolves the issue. Thank you, @how-to-do-frontend.
