### ISSUE TITLE
ICON not showing 

### ISSUE THREAD

**Issue by shadowelite-sec** [nwg-piotr/nwg-dock-hyprland#3]
The nwg-dock is not displaying the application icons for `IDA-Free` , `virtualbox` and `Burp Suite`. However, the icons do appear in nwg-draw and rofi

`application name == IDA`

### nwg-dock : no icon

![20230512_22h21m05s_grim](https://github.com/nwg-piotr/nwg-dock-hyprland/assets/54718375/6b6acc5c-f4be-4b38-a340-6ed48bf5ed1a)

### nwg-draw : 

![20230512_22h22m06s_grim](https://github.com/nwg-piotr/nwg-dock-hyprland/assets/54718375/a8c3acfa-632b-4566-87b0-f6f40151ff12)

**Comment by nwg-piotr** [comment]
I only checked with VirtualBox.

The reason is that the .desktop file name should be `<client_class_name>.desktop`. Meanwhile the class name is `VirtualBox Manager`, while the desktop file name is `virtualbox.desktop`.

I added a workaround for this certain case, but this for sure won't resolve every single similar issue that may occur.

**Comment by nwg-piotr** [comment]
Please re-open it the issue persists for some app. I'll need some more info, if so.

**Comment by shadowelite-sec** [comment]
After updating to <b>nwg-dock-hyprland version 0.1.2</b>, some app icons are not showing, such as `burpsuite` and `ghidra`. This was working in the previous version, <b>nwg-dock-hyprland version 0.1.1</b>.

`vertualbox` and `ida` icons are working now.
 
### nwg-dock-hyprland version 0.1.1:
![20230514_11h41m35s_grim](https://github.com/nwg-piotr/nwg-dock-hyprland/assets/54718375/57279794-a635-48f2-9da2-c5cdd08d071f)

### nwg-dock-hyprland version 0.1.1:  no icons
![20230514_11h46m31s_grim](https://github.com/nwg-piotr/nwg-dock-hyprland/assets/54718375/3276dad9-a19d-4cdb-80eb-6cab41a2ba08)

**Comment by nwg-piotr** [comment]
We will never cover all the badly packaged apps. The only thing the dock knows is the client class, returned by Hyprland:

`"class": "burp-StartBurp"`

Now we seek an icon or a .desktop file named like this. But they are called 'burpsuite' and 'burpsuite.desktop'. This may be fixed for you on 2 levels, both beside my range:

1. make Hyprland return the proper class name, or
2. name the .desktop file after the class name.

The 1st may only be done by Hyprland developers. The 2nd you may do on your machine, by just copying `/usr/share/applications/burpsuite.desktop` to `~/.local/share/applications/` and renaming it to 'burp-StartBurp.desktop`.

![image](https://github.com/nwg-piotr/nwg-dock-hyprland/assets/20579136/2e2c65ff-5d54-4673-a186-e123c1b99f35)

**Comment by shadowelite-sec** [comment]
hmm ok thanks
