### ISSUE TITLE
Installation of go takes minutes. https://github.com/gotk3/gotk3/gtk returns 404. Timeout issue?

### ISSUE THREAD

**Issue by mylinuxforwork** [nwg-piotr/nwg-dock-hyprland#33]
**Describe the bug**
I wanted to try out your dock but the installation takes around 10 minutes. 
It stops for minutes during the go installation when github.com/gotk3/gotk3/gtk appears as installation step.
When I open github.com/gotk3/gotk3/gtk in the browser, I see 404 on GitHub.
It happens during the installation with yay and make build.
Is this a timeout issue?

**Desktop (please complete the following information):**
 - Arch Linux

**Comment by nwg-piotr** [comment]
Hi,

Yes, it takes forever. That's why I provide *-bin packages for all nwg-shell stuff written in golang.

**Comment by mylinuxforwork** [comment]
Thank you.
