### ISSUE TITLE
Setting XDG_CACHE_HOME and/or XDG_DATA_HOME breaks application

### ISSUE THREAD

**Issue by JoelleJS** [nwg-piotr/nwg-dock-hyprland#35]
**Describe the bug**
These are two bugs with setting XDG environment variables:
* Setting `XDG_CACHE_HOME` makes the application look for `nwg-dock-pinned` in the `$HOME/.config` dir:
```
ERRO[0000] Unable to show grid button: open /home/yourusername/.config/nwg-dock-pinned: no such file or directory
```
* Setting `XDG_DATA_HOME` to anything else than `/usr/share` makes the application look for the application images in `$XDG_DATA_HOME/nwg-dock-hyprland/images` instead of `/usr/share/nwg-dock-hyprland/images`, resulting in a panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5e3243]
```

**To Reproduce**
1. Start the application with either environment variable set

**Expected behavior**
* The application looks for `nwg-dock-pinned` in `$XDG_CACHE_HOME`
* The application looks for its images in `/usr/share/nwg-dock-hyprland/images`

**Desktop (please complete the following information):**
 - Linux distribution: Arch Linux
 - go version: go1.22.3 linux/amd64
 - gtk-layer-shell version: 0.8.2-1

**Comment by dlasky** [comment]
needs some work to build but its close

**Comment by nwg-piotr** [comment]
@dlasky Thanks!
