### ISSUE TITLE
Can not switch to app with multiple instances with touch

### ISSUE THREAD

**Issue by ForgotMyPasswd** [nwg-piotr/nwg-dock-hyprland#38]
**Describe the bug**
If an app has multiple windows or instances of that app, such as two instances of the kitty terminal emulator,  the popup to select which of these instances to select appears. However, this menu can't be tapped on and can only be interacted with using a mouse which is inconvenient for 2 in 1 laptop users.

**To Reproduce**
1. Open two sessions of any app
2. Tap on the grouped icon
3. Tap on one of the windows that appear in the pop up

**Expected behavior**
Switch to the window that is tapped from this pop up

**Desktop (please complete the following information):**
 - Linux distribution - EndeavourOS w/ 6.8.9-arch1-2 kernel
 - go version - 2:1.22.3-1
 - gtk-layer-shell version - 0.8.2-1

**Comment by nwg-piotr** [comment]
I have no touch screen device to play with. Which touch event would you like me to connect?

**Comment by ForgotMyPasswd** [comment]
I can't offer much guidance since I'm unfamiliar with how GTK handles touch events, though from a brief look at the documentation `GDK_TOUCH_END` appears to be the event that should be used. Ideally I would like to tap on a program as usual, and be able to tap on instances of that program in the pop up that appears when there are multiple instances. Apologies if my guess was incorrect.

**Comment by nwg-piotr** [comment]
Well, we seem not to have much options. The `GDK_TOUCH_END` event fires together with button release, so it's not a solution. Probably a long press would do the job, but we have no such event in GTK3. We would need a timer between `Gdk.EventType.TOUCH_BEGIN` and `Gdk.EventType.TOUCH_END`. It would be much easier if I had a device to test stuff on.
