### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by vitezprchal** [nwg-piotr/nwg-dock-hyprland#40]
**Describe the bug**
When I click on any application in dock-hyprland, my cursor moves to the centre of the window.

**To Reproduce**
1. Click on any application

**Expected behavior**
A configuration that allows, whether you want it or not

**Screenshots**
- None

**Desktop (please complete the following information):**
 - Linux distribution: :nixos
 - go version - 
 - gtk-layer-shell version -

**Additional context**
- None

**Comment by nwg-piotr** [comment]
This is a Hyprland setting. Set `no_cursor_warps = true` to disable.
