### ISSUE TITLE
FR: Add Position Right?

### ISSUE THREAD

**Issue by aidan-gibson** [nwg-piotr/nwg-dock-hyprland#43]
**Describe the bug**
Position right is not an option. You can do bottom/top/left but not right.

**Expected behavior**
`nwg-dock-hyprland -p "right"` should position on the right.

P.S. Thanks so much for this software!

**Comment by nwg-piotr** [comment]
Hi,

On the very beginning I assumed that the right position makes no sense, at least from the point of view of right-handed users. Adding it is of course possible, but would require some work. Could you explain why you need this?

**Comment by aidan-gibson** [comment]
Left-handed(:

**Comment by nwg-piotr** [comment]
Done. Better late than never. ;)
