### ISSUE TITLE
Randomized order of apps on the dock

### ISSUE THREAD

**Issue by ivangeorgiew** [nwg-piotr/nwg-dock-hyprland#44]
**Describe the bug**
The apps are reordered randomly in the dock due to `hyprctl clients` inconsistent output.

**To Reproduce**
1. Open at least 2 floating apps in the same workspace
2. Switch the app focus using the dock. Do it multiple times.
3. See the apps being reordered sometimes.

**Expected behavior**
The clients returned from `hyprctl clients` should be sorted by class for example, so the order remains consistent.

**Desktop (please complete the following information):**
 - NixOS 24.05
 - go 1.22.4

**Comment by nwg-piotr** [comment]
It would be easy to sort the `clients` slice by the `Class` field value, but in no way can I reproduce the issue on my side. What's your Hyprland version?

**Comment by ivangeorgiew** [comment]
I'm using v0.37.1 since the last time I updated there were issues with hyprland and I will try to delay the update as long as possible. \
Did you use floating apps when testing? \
Even if the ordering is not broken for some hyprland version, doesn't it make sense to sort anyways since it is not a lot of code and is a sort of "double check"?

**Comment by nwg-piotr** [comment]
I'm on v0.41.2, that may make a difference. One way or another, I'll test your changes in the evening an let you know.

**Comment by nwg-piotr** [comment]
Merged.
