### ISSUE TITLE
nwg-dock-hyprland is not launching after updating hyprland to V42.0

### ISSUE THREAD

**Issue by AnkurAlpha** [nwg-piotr/nwg-dock-hyprland#48]
after updating to hyprland v42 , it did as expected , got independent from wlroots and no more using it .
Everything is working flawlessly but I now nwg-dock-hyprland is no more launching , if I run from terminal , then it gives me this output : 
```
─ankur@ankur in ~ 
 ╰─λ nwg-dock-hyprland
INFO[0000] Using auto-detected launcher command: 'nwg-drawer' 
INFO[0000] Using style: /home/ankur/.config/nwg-dock-hyprland/style.css 
FATA[0000] Couldn't list clients: json: cannot unmarshal number into Go struct field client.fullscreen of type bool 

 ╭─ankur@ankur in ~ took 81ms
[🔴] × 
```

**Expected behavior**
it should launch when I run the command on terminal 

**Desktop (please complete the following information):**
 - Distro : Gaurda Linux
 - go version : was never installed in my system, still it was working
 - gtk-layer-shell version :  0.8.2-1

**Additional context**
it can be due to hyprland dropping it's dependency from wlroots completely  , can have a look [here](https://github.com/hyprwm/Hyprland/releases/tag/v0.42.0)

**Comment by nwg-piotr** [comment]
I haven't yet tested my stuff with Hyprland 0.42.0. It's still in Extra-Testing. If it introduces breaking changes, it's not my  fault. I'm leaving for a week on Monday. When I get back, I'll be deciding whether to adapt all my software or drop support for Hyprland.

**Comment by AnkurAlpha** [comment]
Thanks for your reply 

Will be waiting to know what is your final decision

**Comment by nwg-piotr** [comment]
LOL, most likely I won't drop Hyprland support. I just need a reset, so I'll be fishing and drinking beer all the next week. Will try and fix when I'm back.

**Comment by AnkurAlpha** [comment]
Thanks for keeping up the support!!! 😃

**Comment by MaiorDomus** [comment]
Got it working :) 

The problem is in the changed json data being returned from the hyprctl j/clients command. 
There have been some changes made with the fullscreen so in the client struct (hypr.go) I removed FakeFullscreen and changed fullscreenMode into FullscreenClient. Oh and changed the bool of Fullscreen into an int (not sure why that doesn't just return a true or false)

**Comment by TheDarkosGang** [comment]
> Got it working :)
> 
> The problem is in the changed json data being returned from the hyprctl j/clients command. There have been some changes made with the fullscreen so in the client struct (hypr.go) I removed FakeFullscreen and changed fullscreenMode into FullscreenClient. Oh and changed the bool of Fullscreen into an int (not sure why that doesn't just return a true or false)

Could you show me how to fix it?))

**Comment by nwg-piotr** [comment]
> Could you show me how to fix it?))

Sure.

1. `git clone https://github.com/nwg-piotr/nwg-dock-hyprland.git`
2. open the `hypr.go` file in some editor
3. in line 62, replace `bool` with `int `
4. save file
5. `cd nwg-dock-hyprland`
6. `make build`
7. `sudo make install`

**Comment by AnkurAlpha** [comment]
> Got it working :)

Thanks a lot man !!! ❤️
