### ISSUE TITLE
The new -lp option is causing a glitch in case of no-launcher. -nolauncher does not save from this glitch either.

### ISSUE THREAD

**Issue by FireDrop6000** [nwg-piotr/nwg-dock-hyprland#49]
![1723353870_grim](https://github.com/user-attachments/assets/a337f4aa-1a02-4cc9-ad78-bde3ae5e6323)
![1723353844_grim](https://github.com/user-attachments/assets/f03ca317-5ab8-4c04-9902-76d8bf50b69e)
These two pictures show an unnecessary padding where the launcher button was supposed to be. But to be precise I am a no-launcher user. I even tried with "-nolauncher" but this padding persists. Hovering changes colour indicating something was supposed to be there, but clicking it does not work. This padding changes sides on the use of "-lp 'start'". This glitch was not there before the update.

**Comment by nwg-piotr** [comment]
Who on Earth would use `-lp <pos>` and `-nolauncher` arguments together? Either you want the launcher button on "start" or "end" position (`-nolanuncher` makes no sense), or you don't (`-lp` makes no sense).

**Comment by nwg-piotr** [comment]
Should be all right now.

**Comment by FireDrop6000** [comment]
it did. thank you sir.
