### ISSUE TITLE
Dock opens Thunar Bulk Rename instead  Thunar File Manager

### ISSUE THREAD

**Issue by shadowelite-sec** [nwg-piotr/nwg-dock-hyprland#5]
### Description:

When I pin Thunar File Manager to my dock, and click on the launch icon, it opens Thunar Bulk Rename instead. I have tried reinstalling Thunar, but the issue persists.

### Steps to reproduce:

 1.  Pin Thunar File Manager to your dock.
 2.  Click on the launch icon.
 3.  Thunar Bulk Rename should open.

### Expected behavior:

When I click on the launch icon for Thunar File Manager, Thunar File Manager should open.

### Actual behavior:

When I click on the launch icon for Thunar File Manager, Thunar Bulk Rename opens.

###

https://github.com/nwg-piotr/nwg-dock-hyprland/assets/54718375/c9ca2799-bde3-4783-b7e2-7752f2bccc77

 I think it is related to issue #3

**Comment by nwg-piotr** [comment]
You're right. I'll fix it.
