### ISSUE TITLE
how to make dock hide when window opens

### ISSUE THREAD

**Issue by maarutan** [nwg-piotr/nwg-dock-hyprland#52]
![2024-08-14_17-40](https://github.com/user-attachments/assets/bd7beb4b-bb18-4834-af3c-ecf967fc51dd)
 
is it possible to hide the dock when a window opens so that it goes into -d mode, and when there is no window everything is as usual, before this I used bash scripts but I would like it to be built-in

**Comment by nwg-piotr** [comment]
Not implemented, but doable. I'll consider adding this in further development.

**Comment by maarutan** [comment]
[https://github.com/nwg-piotr/nwg-dock-hyprland/issues/52#issuecomment-2288636020](url)
in the next update???

I'll be looking forward to it )))))))

**Comment by nwg-piotr** [comment]
I took a closer look at it, and came to the conclusion that I misunderstood your request. The dock is being auto-hidden on icon click, if started in `-d` mode. If you don't use this flag, there's no way to switch the autohiDe at run time.

**Comment by maarutan** [comment]
and if I want it to always be displayed on top of windows, that is -top, and when a window opens, it hides, and if there is no window, it is always in active mode, and plus if there is an active window, then when in vision, it performs the function -d, that is, show the dock

**Comment by nwg-piotr** [comment]
You may want to take a look at #55.
