### ISSUE TITLE
Not work on nixos

### ISSUE THREAD

**Issue by binarylinuxx** [nwg-piotr/nwg-dock-hyprland#54]
try launch on nixos im already installed nwg drawer but get this error:
╭─░▒▓      ~/nwg-dock-hyprland  on    master !3 
╰─ nwg-dock-hyprland                                                                       ─╯
INFO[0000] Using auto-detected launcher command: 'nwg-drawer'
INFO[0000] Using style: /home/binaryl/.config/nwg-dock-hyprland/style.css
FATA[0000] Couldn't list clients: json: cannot unmarshal number into Go struct field client.fullscreen of type bool

╭─░▒▓      ~/nwg-dock-hyprland  on    master !3 ······· 1 ✘  at 08:42:11 PM   ▓▒░─╮
╰─                                                                                         ─╯

**Comment by nwg-piotr** [comment]
Ask your packager to update to v0.2.2.

https://github.com/nwg-piotr/nwg-dock-hyprland/releases/tag/v0.2.2
