### ISSUE TITLE
How to show/hide dock programatically instead of toggling?

### ISSUE THREAD

**Issue by karamanliev** [nwg-piotr/nwg-dock-hyprland#55]
I made a script to show the dock when there are no windows after workspace change and to make it in `-d (autohide)`  mode when there are windows on the workspace.

Unfortunately I can't find a way to do it currently because I can't find a way to do it, because there is an option only to toggle it.

Also, is it possible to show the dock on every monitor? I tried launching multiple instances but it didn't work.

Am I missing something?

**Comment by nwg-piotr** [comment]
You are right. We have no way to turn on/off specifically, just USR1 to toggle.

**Comment by karamanliev** [comment]
I implemented an "intelligent" dock, using hyprland IPC socket. It kind of works, but it's getting quite complex, because of no real on/off state. Now I have to do it for multiple monitors 🤣

https://github.com/user-attachments/assets/82cc5637-3672-4ddc-a282-d5e8c6872ae7

**Comment by nwg-piotr** [comment]
The hardest part is to decide which signals to use for show/hide, as we need to leave USR1 as is, to avoid breaking users' configs. The code itself would be easy.

**Comment by karamanliev** [comment]
I currently implemented it for `workspace`, `openwindow`, `closewindow`, `activespecial` and `activespecial`, but there might be more like `changefloatingmode` and `movewindow`.

**Comment by nwg-piotr** [comment]
Maybe, instead of external scripting, it would make sense to add such behaviour as a dock option?

**Comment by karamanliev** [comment]
Oh, it would be awesome!

**Comment by nwg-piotr** [comment]
Make a list which event should trigger which action, e.g.:

`openwindow` - hide
`closewindow` - show
(...)

and so on, and I'll try to do so.

**Comment by karamanliev** [comment]
I'm not sure if it would be that simple. In my opinion, active workspace window count and maybe window positions should be tracked on different signals. And then, depending on the result the dock should be hidden or shown.

**Comment by nwg-piotr** [comment]
Well, maybe it makes more sense to leave it for an external script. I can imagine dozen of issues submitted by people who want stuff work differently.

**Comment by karamanliev** [comment]
Yeah, you're right. Just a simple `nwg-dock-hyprland --show` / `nwg-dock-hyprland --hide` switch would suffice. This would not disrupt the current toggle behaviour.

A bonus would be, if it's possible to add something like `--show -o monitorID` to force showing on a specified display. This currently works with `-d`.  The dock shows on the display where you hover the hotspot.

**Comment by nwg-piotr** [comment]
I'll stick to signals. In addition to the current `USR1` for Toggle, I'll make:

- `SIGRTMIN+1` for Toggle,
- `SIGRTMIN+2` for Show,
- `SIGRTMIN+3` for Hide.

Basic code is ready.

> A bonus would be (...)

This would be difficult, if even possible.

**Comment by nwg-piotr** [comment]
@karamanliev Would you mind sharing your script, when adjusted to the latest changes? We could add it to the repo.

**Comment by maarutan** [comment]
I can't wait to see your script ;))))

**Comment by karamanliev** [comment]
Basically works perfect on a single monitor with `-d` and `-r` and on multiple monitors with `-r`. Not so good with `-d`. If anyone has any ideas how to make it work, please do. I think process should be killed and started again and something like a debounce ot throttle should be added so it doesn't run multiple times if switching very fast between monitors. I'm not so good at bash 🤣

There's also no event to track when a window has ended moving or something to be able to hide it if you move a floating window with mouse.

https://github.com/user-attachments/assets/72902b94-a26e-462c-8af2-b5147ab550d6

https://github.com/user-attachments/assets/55bd9cb0-0fe4-4a57-a25f-e186e7bd57dc

```sh
#!/usr/bin/env bash

DOCK_HEIGHT=120
INITIAL_LAUNCH_FLAGS=(-notooltips -d -i 64 -w 10 -mb 6 -hd 0 -c "rofi -show drun" -ico "/usr/share/icons/Papirus-Dark/symbolic/actions/view-app-grid-symbolic.svg")
HIDE_SIGNAL="pkill -37 -f nwg-dock-hyprland"
SHOW_SIGNAL="pkill -36 -f nwg-dock-hyprland"

toggle_dock() {
  if [ "$1" = "show" ]; then
    $SHOW_SIGNAL
  else
    $HIDE_SIGNAL
  fi
}

get_active_ws_id() {
  local ws_id=$(echo "$1" | awk 'NR==2')
  local special_ws_id=$(echo "$1" | awk 'NR==3')

  if [ "$special_ws_id" -eq 0 ]; then
    echo "$ws_id"
  else
    echo "$special_ws_id"
  fi
}

show_hide_dock() {
  local monitor_info=$(hyprctl monitors -j | jq -r '.[] | select (.focused == true) | .height, .activeWorkspace.id, .specialWorkspace.id')
  local monitor_height=$(echo "$monitor_info" | awk 'NR==1')
  local ws_id=$(get_active_ws_id "$monitor_info")
  local window_count=$(hyprctl workspaces -j | jq ".[] | select(.id == $ws_id) | .windows")

  if [ "$window_count" -eq 0 ]; then
    toggle_dock "show"
    return
  fi

  # get all windows Y pos and Y size on the active workspace
  local windows_data=$(hyprctl clients -j | jq -c ".[] | select(.workspace.id == $ws_id) | {at: .at[1], size: .size[1]}")
  local should_show=1

  while IFS= read -r window; do
    local pos_y=$(echo "$window" | jq -r '.at')
    local size_y=$(echo "$window" | jq -r '.size')
    local free_space=$((monitor_height - pos_y - size_y))

    if [ "$free_space" -lt "$DOCK_HEIGHT" ]; then
      should_show=0
      break
    fi
  done <<<"$windows_data"

  if [ "$should_show" -eq 1 ]; then
    toggle_dock "show"
  else
    toggle_dock "hide"
  fi
}

initial_dock_launch() {
  nwg-dock-hyprland "${INITIAL_LAUNCH_FLAGS[@]}" >/dev/null 2>&1 &

  # need to wait this much only if using '-d', I don't know why. Needs only 0.1 with '-r'
  sleep 0.6 && show_hide_dock
}

function handle {
  case $1 in
  changefloatingmode* | workspacev2* | closewindow* | openwindow* | activespecial*)
    show_hide_dock
    ;;

  focusedmon*)
    # buggy with "-d" if you hover on the hotspot on one monitor it stops moving between monitors, works perfect with "-r"
    toggle_dock "hide" && show_hide_dock
    ;;
  esac
}

initial_dock_launch

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
```

**Comment by karamanliev** [comment]
Hacky, but it does the job.

https://github.com/user-attachments/assets/130c16ee-d9ba-466e-b137-743b744fe799

**Comment by nwg-piotr** [comment]
> I think the process should be killed and started again and something like a debounce ot throttle should be added so it doesn't run multiple times if switching very fast between monitors.

Pay attention to the fact, that you are unable to run multiple instances of the program. Depending on the arguments in use, it'll behave differently, but 2 instances should be impossible in any case.

**Comment by karamanliev** [comment]
> Pay attention to the fact, that you are unable to run multiple instances of the program. Depending on the arguments in use, it'll behave differently, but 2 instances should be impossible in any case.

Yep, it almost worked when relaunching with `pkill -f nwg-dock-hyprland` when switching between monitors, but it was not perfect. I'll revisit it tomorrow, when I have some free time.

**Comment by maarutan** [comment]
The script doesn't work for me, can you tell me in detail how to run it?

**Comment by karamanliev** [comment]
> The script doesn't work for me, can you tell me in detail how to run it?

just  `chmod +x path/to/script.sh`, then `exec-once = path/to/script.sh` in your hyprland config.

Try to run it in your terminal first.  And tell me if you're getting any errors.

**Comment by maarutan** [comment]
At the same time, autoHide does not work for me when aiming at a hot spot

**Comment by karamanliev** [comment]
> At the same time, autoHide does not work for me when aiming at a hot spot

Change `-r` with `-d` for autohide

**Comment by maarutan** [comment]
I already have it at -d

`DOCK_HEIGHT=120
INITIAL_LAUNCH_FLAGS=(-notooltips -d -i 64 -w 10 -mb 6 -hd 0 -c "rofi -show drun")
HIDE_SIGNAL="pkill -37 -f nwg-dock-hyprland"
SHOW_SIGNAL="pkill -36 -f nwg-dock-hyprland"

`

**Comment by karamanliev** [comment]
lol, remove `-notooltips`. I forked the repo and built a binary for myself with it.

**Comment by maarutan** [comment]
lol thanks for the script ^^

**Comment by maarutan** [comment]
I'm sorry, but how did you style the application launcher???

**Comment by karamanliev** [comment]
```css
/*-----   ~/.config/nwg-dock-hyprland/style.css   -----*/

window {
  background: rgba(34, 36, 54, 0.5);
  border-radius: 16px;
  border-style: none;
  border-width: 0px;
  border-color: rgba(156, 142, 122, 0.7);
}

#box {
  /* Define attributes of the box surrounding icons here */
  padding: 10px;
}

#active {
  /* This is to underline the button representing the currently active window */
  border-bottom: solid 0px;
  border-color: rgba(255, 255, 255, 0.3);
}

button,
image {
  background: none;
  border-style: none;
  box-shadow: none;
  color: #999;
}

button {
  padding: 4px;
  border-radius: 16px;
  margin-left: 4px;
  margin-right: 4px;
  margin-bottom: 4px;
  color: #eee;
  font-size: 12px;
}

button:hover {
  background-color: rgba(192, 202, 245, 0.3);
}

button:focus {
  box-shadow: none;
}
```

**Comment by maarutan** [comment]
my app launcher is orange i want to change it to white or purple

**Comment by karamanliev** [comment]
It's in the `README`. Use `-ico` and provide path for your own icon.
