### ISSUE TITLE
FATA[0000] Couldn't list clients: json: cannot unmarshal bool into Go struct field client.fullscreen of type int  ❯ 

### ISSUE THREAD

**Issue by ProbablyNotToxicity** [nwg-piotr/nwg-dock-hyprland#58]
when i try to start the nwg-dock-hyprland it shows this error. idk how to fix

**Comment by nwg-piotr** [comment]
You must be on an old version. It has been fixed two releases ago.

**Comment by ProbablyNotToxicity** [comment]
> You must be on an old version. It has been fixed two releases ago.

i downloaded from pacman so this might be the issue

**Comment by nwg-piotr** [comment]
Check `nwg-dock-hyprland -v` from terminal.

**Comment by ProbablyNotToxicity** [comment]
> Check `nwg-dock-hyprland -v` from terminal.

version 0.3.0

**Comment by nwg-piotr** [comment]
Dunno what's going on. This version is free of this big for sure.

**Comment by nwg-piotr** [comment]
What's your Hyprland version?

**Comment by ProbablyNotToxicity** [comment]
> What's your Hyprland version?

v0.41.2

**Comment by nwg-piotr** [comment]
That's it. The latest dock expects 0.42.

**Comment by nwg-piotr** [comment]
> That's it. The latest dock expects 0.42.

@Antiz96, could you please mark it in the package, when you have a minute?

**Comment by ProbablyNotToxicity** [comment]
> That's it. The latest dock expects 0.42.

now i got a new problem that i will need to ask in hyprland github. hyprland doesnt start after update

**Comment by Antiz96** [comment]
> > That's it. The latest dock expects Hyprland 0.42.
> 
> @Antiz96, could you please mark it in the package, when you have a minute?

This is not a packaging issue or a missing mark at the package/pkgbuild level.

Hyprland 0.42 has been published in the [[extra] repository](https://archlinux.org/packages/extra/x86_64/hyprland/) at the beginning of august while the latest nwg-hyprland-dock has been published in [[extra] repository](https://archlinux.org/packages/extra/x86_64/nwg-dock-hyprland/) yesterday.
The situation @ProbablyNotToxicity is facing is a [partial upgrade](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported). As you can see from the link, partial upgrades are subject to breakages and unsupported.

@ProbablyNotToxicity You can just run `pacman -Syu` to update your system **completely** and fix the issue. You should avoid commands like `pacman -Sy package-name` in the future.

**Comment by ProbablyNotToxicity** [comment]
> Hyprland 0.42 has been published in the [[extra] repository](https://archlinux.org/packages/extra/x86_64/hyprland/) at the beginning of august while the latest nwg-hyprland-dock has been published in [[extra] repository](https://archlinux.org/packages/extra/x86_64/nwg-dock-hyprland/) yesterday.

> @ProbablyNotToxicity You can just run `pacman -Syu` to update your system **completely** and fix the issue. You should avoid commands like `pacman -Sy package-name` in the future.


thx its fixed now and dock is working

**Comment by nwg-piotr** [comment]
> > > That's it. The latest dock expects Hyprland 0.42.
> > 
> > @Antiz96, could you please mark it in the package, when you have a minute?
> 
> This is not a packaging issue or a missing mark at the package/pkgbuild level.
> 
> Hyprland 0.42 has been published in the [[extra] repository](https://archlinux.org/packages/extra/x86_64/hyprland/) at the beginning of august while the latest nwg-hyprland-dock has been published in [[extra] repository](https://archlinux.org/packages/extra/x86_64/nwg-dock-hyprland/) yesterday.
> The situation @ProbablyNotToxicity is facing is a [partial upgrade](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported). As you can see from the link, partial upgrades are prone to breakages and unsupported.
> 
> @ProbablyNotToxicity You can just run `pacman -Syu` to update your system **completely** and fix the issue. You should avoid commands like `pacman -Sy package-name` in the future.

This was really informative. Thank you.

**Comment by Antiz96** [comment]
> > > > That's it. The latest dock expects Hyprland 0.42.
> > > 
> > > 
> > > @Antiz96, could you please mark it in the package, when you have a minute?
> > 
> > 
> > This is not a packaging issue or a missing mark at the package/pkgbuild level.
> > Hyprland 0.42 has been published in the [[extra] repository](https://archlinux.org/packages/extra/x86_64/hyprland/) at the beginning of august while the latest nwg-hyprland-dock has been published in [[extra] repository](https://archlinux.org/packages/extra/x86_64/nwg-dock-hyprland/) yesterday.
> > The situation @ProbablyNotToxicity is facing is a [partial upgrade](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported). As you can see from the link, partial upgrades are prone to breakages and unsupported.
> > @ProbablyNotToxicity You can just run `pacman -Syu` to update your system **completely** and fix the issue. You should avoid commands like `pacman -Sy package-name` in the future.
> 
> This was really informative. Thank you.

No problem :)

**Comment by Antiz96** [comment]
> > Hyprland 0.42 has been published in the [[extra] repository](https://archlinux.org/packages/extra/x86_64/hyprland/) at the beginning of august while the latest nwg-hyprland-dock has been published in [[extra] repository](https://archlinux.org/packages/extra/x86_64/nwg-dock-hyprland/) yesterday.
> 
> > @ProbablyNotToxicity You can just run `pacman -Syu` to update your system **completely** and fix the issue. You should avoid commands like `pacman -Sy package-name` in the future.
> 
> thx its fixed now and dock is working

You're welcome :)
