### ISSUE TITLE
[Feature Request] Changing position of app indicators

### ISSUE THREAD

**Issue by odomingao** [nwg-piotr/nwg-dock-hyprland#62]
Please add an option to change the position of the app indicator, from bottom to left/right. In my opinion, bottom indicators look very bad for vertical docks/panels. Thank you!

**Comment by nwg-piotr** [comment]
I'm not sure what you mean. What is app indicator?

**Comment by odomingao** [comment]
> I'm not sure what you mean. What is app indicator?

I'm talking about the blue dots that appear below the app icon in the dock. One dot for one window, 2+ dots for two+ windows.

**Comment by nwg-piotr** [comment]
Ah, ok. I'll check what could be done.

**Comment by nwg-piotr** [comment]
Well, I'm not sure if I like the result, do you?

![image](https://github.com/user-attachments/assets/b3b7a3ad-17de-4911-816d-9749b7cba841)

**Comment by odomingao** [comment]
Looks better in my opinion, though the launcher icon appears to be misaligned now?

**Comment by nwg-piotr** [comment]
This seems to be aligned well.

![obraz](https://github.com/user-attachments/assets/2b1d37dd-6805-4762-85e0-027f7a4f9166)

**Comment by nwg-piotr** [comment]
In case you'd like to test:

1. install `git` & `go` packages
2. `git clone https://github.com/nwg-piotr/nwg-dock-hyprland.git -b dots`
3. `cd nwg-dock-hyprland`
4. `go run . <place-your-args-here>`

First build will take quite a lot of time.

**Comment by nwg-piotr** [comment]
Alright, I'll merge and release tonight.
