### ISSUE TITLE
[Question] nwg-dock and nwg-dock-hyprland

### ISSUE THREAD

**Issue by donovanglover** [nwg-piotr/nwg-dock-hyprland#7]
I was looking through the source code for `nwg-dock-hyprland` and many parts are the same as `nwg-dock`. I feel like one repository that supports both Sway and Hyprland would be easier to maintain in terms of feature parity / bug fixes / etc.

I read https://github.com/nwg-piotr/nwg-shell/discussions/91 and think that this was the original idea, but ultimately a separate app was made. Would love more insight on this decision.

**Comment by nwg-piotr** [comment]
Initially I tried to add Hyprland support to nwg-dock, but the code was getting too complicated. They're much easier to debug and maintain as separate apps.

**Comment by donovanglover** [comment]
Understandable. Thanks for all your work on nwg-shell!
