### ISSUE TITLE
Feature: make hotspot for autohide full width of screen

### ISSUE THREAD

**Issue by notoyz** [nwg-piotr/nwg-dock-hyprland#8]
Small annoyance but i often miss where the dock is supposed to be on the first attempt which requires me to raise my mouse and lower it again in the correct spot.

Seeing as I have nothing else bound to any hotspots on the bottom of the screen, making the hotspot full-width would make for a more consistent experience.

**Comment by nwg-piotr** [comment]
I gave it a try, but it has a side effect. It's too easy to show the dock by accident. And you need take an action to hide it: either use a key binding, or point and leave the dock window. I don't like it.
