### ISSUE TITLE
Give icon search priority to the user folder `~/.local/share/applications`

### ISSUE THREAD

**Issue by e-tho** [nwg-piotr/nwg-dock-hyprland#9]
This would allow users to overwrite an application's icon by copying its `.desktop` file into the user folder to modify it

**Comment by nwg-piotr** [comment]
That's what it already looks like, unless you specified `XDG_DATA_HOME`. The first in the slice item returned by the getAppDirs() function is:

```go
    if xdgDataHome != "" {
        dirs = append(dirs, filepath.Join(xdgDataHome, "applications"))
    } else if home != "" {
        dirs = append(dirs, filepath.Join(home, ".local/share/applications"))
    }
```

See: https://github.com/nwg-piotr/nwg-dock-hyprland/blob/f20e5178070f45f98b7abe25b5318eb3e583724b/tools.go#L467

**Comment by nwg-piotr** [comment]
The culprit is the `break` statement missing from the loop that searches paths in the `getIcon()` function. I'll fix it.

**Comment by e-tho** [comment]
Thanks. This caused the home directory to be used as a fallback only
